<?php

namespace AppBundle\Repository;

/**
 * UserIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserIncomeRepository extends \Doctrine\ORM\EntityRepository
{
}
